(deftheme wombat2
  "Created 2013-02-04.")

(custom-theme-set-variables
 'wombat2
 '(ansi-color-names-vector ["#242424" "#e5786d" "#95e454" "#cae682" "#8ac6f2" "#333366" "#ccaa8f" "#f6f3e8"]))

(custom-theme-set-faces
 'wombat2
 '(default ((((class color) (min-colors 89)) (:background "#242424" :foreground "#f6f3e8"))))
 '(cursor ((((class color) (min-colors 89)) (:background "#656565"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "#ddaa6f" :weight bold))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(highlight ((((class color) (min-colors 89)) (:background "#454545" :foreground "#ffffff" :underline t))))
 '(region ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#333366" :foreground "#f6f3e8"))))
 '(trailing-whitespace ((t (:background "#cc9393"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#7f9f7f" :inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:foreground "#cc3333"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#e5786d"))))
 '(font-lock-doc-face ((t (:foreground "#8fb28f" :inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#dcdccc"))))
 '(font-lock-preprocessor-face ((t (:foreground "#8cd0d3" :inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#92a65e" :weight bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(button ((((class color) (min-colors 89)) (:background "#333333" :foreground "#f6f3e8"))))
 '(link ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#e5786d" :underline t))))
 '(fringe ((((class color) (min-colors 89)) (:background "#303030"))))
 '(header-line ((((class color) (min-colors 89)) (:background "#303030" :foreground "#e7f6da"))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((((class color) (min-colors 89)) (:background "#444444" :foreground "#f6f3e8"))))
 '(mode-line-buffer-id ((t (:weight bold :foreground "#f0dfaf"))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:background "#444444" :foreground "#857b6f"))))
 '(isearch ((((class color) (min-colors 89)) (:background "#343434" :foreground "#857b6f"))))
 '(isearch-fail ((t (:foreground "#dcdccc" :background "#8c5353"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#384048" :foreground "#a0a8b0"))))
 '(match ((t (:weight bold :foreground "#dfaf8f" :background "#2b2b2b"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch)))))
 '(gnus-group-news-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-news-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-news-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-news-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-news-4 ((((class color) (min-colors 89)) (:weight bold :foreground "#99968b"))))
 '(gnus-group-news-4-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-news-5 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-news-5-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-news-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-group-mail-1 ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-group-mail-1-low ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(gnus-group-mail-2 ((((class color) (min-colors 89)) (:weight bold :foreground "#cae682"))))
 '(gnus-group-mail-2-low ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-group-mail-3 ((((class color) (min-colors 89)) (:weight bold :foreground "#ccaa8f"))))
 '(gnus-group-mail-3-low ((((class color) (min-colors 89)) (:foreground "#ccaa8f"))))
 '(gnus-group-mail-low ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(gnus-header-content ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-from ((((class color) (min-colors 89)) (:weight bold :foreground "#95e454"))))
 '(gnus-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(gnus-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2"))))
 '(gnus-header-newsgroups ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-name ((((class color) (min-colors 89)) (:foreground "#8ac6f2" :weight bold))))
 '(message-header-cc ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-other ((((class color) (min-colors 89)) (:foreground "#95e454"))))
 '(message-header-subject ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-header-to ((((class color) (min-colors 89)) (:foreground "#cae682"))))
 '(message-cited-text ((((class color) (min-colors 89)) (:foreground "#99968b"))))
 '(message-separator ((((class color) (min-colors 89)) (:foreground "#e5786d" :weight bold)))))

(provide-theme 'wombat2)
